
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 19 19:24:23 CET 2015
//----------------------------------------------------

package fsb.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ENDINIT = 41;
  public static final int SHARED = 23;
  public static final int BARRIER = 28;
  public static final int PUT = 36;
  public static final int C_COMMENT = 54;
  public static final int LOAD = 24;
  public static final int STORE = 25;
  public static final int NONATOMIC = 38;
  public static final int CAS = 31;
  public static final int RIGHTPAREN = 19;
  public static final int ASSUME = 48;
  public static final int PC = 45;
  public static final int GREATER = 8;
  public static final int SEMI = 12;
  public static final int ENDATOMIC = 47;
  public static final int INIT = 40;
  public static final int ASSERT = 42;
  public static final int LESS = 7;
  public static final int MINUS = 3;
  public static final int LEFTPAREN = 18;
  public static final int NOT = 11;
  public static final int AND = 9;
  public static final int CHOOSE = 49;
  public static final int NOP = 29;
  public static final int OR = 10;
  public static final int COMMA = 14;
  public static final int GET = 35;
  public static final int PLUS = 2;
  public static final int ASSIGN = 15;
  public static final int IF = 26;
  public static final int PROCESS = 39;
  public static final int EOF = 0;
  public static final int EQUAL = 5;
  public static final int TRUE = 50;
  public static final int ATOMIC = 37;
  public static final int RIGHTCURLY = 21;
  public static final int error = 1;
  public static final int MUL = 4;
  public static final int NUMBER = 52;
  public static final int NEQ = 6;
  public static final int IDENT = 53;
  public static final int LEFTCURLY = 20;
  public static final int ATOMICDEC = 33;
  public static final int RGA = 34;
  public static final int RIGHTBRACE = 17;
  public static final int COLON = 13;
  public static final int ALLOCATE = 30;
  public static final int GOTO = 27;
  public static final int FINAL = 43;
  public static final int LEFTBRACE = 16;
  public static final int BEGINATOMIC = 46;
  public static final int LOCAL = 22;
  public static final int FALSE = 51;
  public static final int SWAP = 32;
  public static final int ALWAYS = 44;
}

